# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
$env_var\
$directory\
$git_branch\
$python\
$direnv\
$sudo"""

add_newline = false

[character]
success_symbol = "[➜](bold green)"

[python]
detect_extensions = []
detect_folders = [".venv"]

[env_var.AWS_PROFILE]
variable = "AWS_PROFILE"
format = "\\[[$env_value](bold red)\\] "
