[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = "root: $available.eng(2)"

[[block]]
block = "cpu"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = " $percentage"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"
