[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = " $icon $available "

[[block]]
block = "cpu"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = " $percentage"

[[block]]
block = "time"
interval = 30
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
