[mgr]
prepend_keymap = [
  {on = "?", run = "help", desc = "Open help"},
  {on = [
    "c",
    "i",
  ], run = '''shell --orphan -- xclip -selection clipboard -t "$(file -b --mime-type %h)" -i %h''', desc = "Copy hovered file to clipboard as image data"},
  {on = [
    "c",
    "u",
  ], run = '''shell --orphan -- for p in %s; do echo "file://$p"; done | xclip -i -selection clipboard -t text/uri-list''', desc = "Copy selected files to clipboard as files"},
  {on = "z", run = "plugin zoxide", desc = "Cd to a directory via zoxide"},
  {on = "Z", run = "plugin fzf", desc = "Cd to a directory or reveal a file via fzf"},
  {on = "1", run = "plugin relative-motions-compat 1", desc = "Relative motion 1"},
  {on = "2", run = "plugin relative-motions-compat 2", desc = "Relative motion 2"},
  {on = "3", run = "plugin relative-motions-compat 3", desc = "Relative motion 3"},
  {on = "4", run = "plugin relative-motions-compat 4", desc = "Relative motion 4"},
  {on = "5", run = "plugin relative-motions-compat 5", desc = "Relative motion 5"},
  {on = "6", run = "plugin relative-motions-compat 6", desc = "Relative motion 6"},
  {on = "7", run = "plugin relative-motions-compat 7", desc = "Relative motion 7"},
  {on = "8", run = "plugin relative-motions-compat 8", desc = "Relative motion 8"},
  {on = "9", run = "plugin relative-motions-compat 9", desc = "Relative motion 9"},
]
